# Site settings
title: Robin Kwong | Project management in newsrooms
baseurl: ""
url: "https://www.robinkwong.com"
description: "Personal website of Robin Kwong, New Formats Editor at The Wall Street Journal, where he writes about project management in newsrooms and design thinking in journalism"
# Build settings
include: [_pages]
markdown: kramdown
encoding: utf-8
permalink: /:year/:month/:title
sass:
  style: compressed
plugins_dir:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from